#!/bin/sh
# $Id: edit,v 1.2 2014/01/15 23:20:05 drmiller Exp $

pgm=${0}
if [[ -L ${pgm} ]]; then
        pgm=$(readlink ${pgm})
fi
cd ${pgm%/*}

path="wang700.jar"
macos="../../../Wang700.app/Contents/MacOS"
if [[ ! -f ${path} && -f ${macos}/${path} ]]; then
	path="${macos}/${path}"
fi

exec java -cp ${path} w700_edit "${@}"
