#!/bin/sh
# $Id: INSTALL,v 1.4 2013/12/09 17:04:26 drmiller Exp $

if [[ -d progs ]]; then
	mkdir -p ~/Wang700Files
	cp -v progs/* ~/Wang700Files
fi
base="wang700"
title="Wang700"
if [[ ( -d ~/.gnome || -d ~/.gnome2 ) && -d ~/Desktop ]]; then
	echo "installing GNOME desktop shortcut..."
	export WANG700PATH=${PWD}
	cat ${base}.desktop.tmplt | while read line; do
		eval "echo \"${line}\""
	done >~/Desktop/${title}.desktop
fi

echo "Ready to launch ${PWD}/run"
