#!/bin/sh
# $Id: run,v 1.3 2012/02/19 21:23:58 drmiller Exp $

pgm=${0}
if [[ -L ${pgm} ]]; then
        pgm=$(readlink ${pgm})
fi
cd ${pgm%/*}

opts=""
if [[ ${WANG700_HOST:-not-set} != "not-set" ]]; then
	opts="-w"
fi

exec java -jar wang700.jar ${opts}
