#!/bin/sh
# $Id: txt2wng,v 1.1 2013/12/04 23:03:25 drmiller Exp $

pgm=${0}
if [[ -L ${pgm} ]]; then
        pgm=$(readlink ${pgm})
fi
cd ${pgm%/*}

opts=""

exec java -cp wang1200.jar txt2wng ${opts}
