#!/bin/bash
# $Id: catscope,v 1.3 2011/12/16 14:21:37 drmiller Exp $

rows=(90 100)

bmptopnm_f() {
	local file=${1}
	shift
	if [[ ${#txt[*]} -gt 0 ]]; then
		bmptopnm ${file} | pnmcut ${*} | pnmpad -left 100
	else
		bmptopnm ${file} | pnmcut ${*}
	fi
	return $?
}

unset out txt
cut=114
while getopts "o:c:t:r:" op; do
	case ${op} in
	o)	out=${OPTARG};;
	c)	cut=${OPTARG};;
	t)	txt=(${OPTARG});;
	r)	rows=(${OPTARG});;
	esac
done
shift $((OPTIND-1))

if [[ ${#} -lt 2 ]]; then
	echo "Usage: $0 [-o basename] [-c cutrow] <main> <second> [<third>...]" >&2
	echo "Crops ch2 BMP waveforms and appends to main." >&2
	echo "Assumes all waveforms have same settings." >&2
	echo "Outputs a PNG format image." >&2
	exit 1
fi

main=${1}
shift

if [[ -z ${out} ]]; then
	out="${main%.*}"
fi
in="${out}.$$"
bmptopnm_f ${main} -bottom 213 >${in}

j=("${@}")
n=${#j[*]}
x=0
while [[ ${x} -lt ${n} ]]; do
	i=${j[x]}
	((x+=1))
	if [[ ${x} -eq ${n} ]]; then b=233
	else b=213; fi
	bmptopnm_f ${i} -top ${cut} -bottom ${b} | \
		pnmcat -topbottom -jleft ${in} - >${out}.pnm
	if [[ $? -ne 0 ]]; then exit 1; fi
	mv ${out}.pnm ${in}
	if [[ $? -ne 0 ]]; then exit 1; fi
done

if [[ ${#txt[*]} -gt 0 ]]; then
	args=()
	x=0
	r=${rows[x]}
	for t in ${txt[*]}; do
		args[${#args[*]}]="-y"
		args[${#args[*]}]="${r}"
		args[${#args[*]}]="-text"
		args[${#args[*]}]="${t}"
		((x+=1))
		if [[ ${x} -ge ${#rows[*]} ]]; then ((x=${#rows[*]}-1)); fi
		((r+=rows[x]))
	done
	ppmlabel -x 5 ${args[*]} ${in} | pnmtopng >${out}.png
else
	pnmtopng ${in} >${out}.png
	if [[ $? -ne 0 ]]; then exit 1; fi
fi
rm -f ${in}
