#!/bin/sh
# $Id: edit,v 1.3 2014/01/15 23:20:04 drmiller Exp $

pgm=${0}
if [[ -L ${pgm} ]]; then
        pgm=$(readlink ${pgm})
fi
cd ${pgm%/*}

path="wang600.jar"
macos="../../../Wang600.app/Contents/MacOS"
if [[ ! -f ${path} && -f ${macos}/${path} ]]; then
	path="${macos}/${path}"
fi

exec java -cp "${path}" w600_edit "${@}"
