#!/bin/sh
# $Id: INSTALL,v 1.6 2012/02/01 23:03:40 drmiller Exp $

if [[ -d progs ]]; then
	mkdir -p ~/Wang600Files
	cp -v progs/* ~/Wang600Files
fi
base="wang600"
title="Wang600"
if [[ ( -d ~/.gnome || -d ~/.gnome2 ) && -d ~/Desktop ]]; then
	echo "installing GNOME desktop shortcut..."
	export WANG600PATH=${PWD}
	cat wang600.desktop.tmplt | while read line; do
		eval "echo \"${line}\""
	done >~/Desktop/wang600.desktop
elif [[ -f ~/.CFUserTextEncoding && -d ~/Desktop ]]; then
	echo "installing OSX desktop shortcut..."
	rm -rf ~/Desktop/${title}.app
	mkdir -p ~/Desktop/${title}.app/Contents/{Resources,MacOS}
	cp ${base}.plist.tmplt ~/Desktop/${title}.app/Contents/Info.plist
	ln -s ${PWD}/run ~/Desktop/${title}.app/Contents/MacOS/
	cp icons/${base}-*x*.icns ~/Desktop/${title}.app/Contents/Resources/
fi
echo "Ready to launch ${PWD}/run"
