# $Id: Makefile.ship,v 1.13 2013/11/13 23:34:00 drmiller Exp $

COPTS =

VPATH = ../common

CFLAGS += -D__wang600__ -I../common -I.

OBJS = wang_sys.o wang_sim_cmd.o \
	w600_decode.o wang_exec.o wang_gui.o

ROM = wang600.rom

EXE = w600-sim

SPCL = plotter_chrgen.dat

# Order is significant, until we setup dependencies
COMMON_CLASSES = \
		SuffFileFilter.class \
		SuffFileChooser.class \
		Wang_Colors.class \
		Wang_Keys.class \
		Wang_Properties.class \
		Wang_PropertyEditor.class \
		Wang_CharConverter.class \
		Wang_Indicator.class \
		Wang_InputDevice.class \
		Wang_Core.class \
		Wang_UI.class \
		Wang_ErrorLight.class \
		Wang_TapeDevice.class \
		Wang_TapeDrive.class \
		Wang_OutputDevice.class \
		Wang_Paper.class \
		IBM_Selectric.class \
		Wang_Plotter.class \
		Wang_InputOutputWriter.class \
		Wang_PlottingOutputWriter.class \
		Wang_OutputWriter.class \
		Wang_CN36_Type2.class \
		Wang_Display.class \
		Wang_Help.class \
		Wang_Keyboard.class \
		Wang_Printer.class \
		Wang_XROM.class

W600_CLASSES = \
	Wang600.class
#	Wang600_SimulatorPipe.class \
#	Wang600_SimulatorJava.class

FONTDIR = $(shell if [[ -d ~/.fonts ]]; then echo ~/.fonts; elif [[ -d ~/Library/Fonts ]]; then echo ~/Library/Fonts; fi)
FONTDEST =
FONTS = $(notdir $(wildcard ../common/fonts/*.ttf))

XTRA = 

DASM = dw600.o loaducode_txt.o

all: $(EXE) w600_fe.class

CFLAGS += -g -O3 $(COPTS)

w600-dasm: wang-dasm.o $(DASM)
	$(CC) $(CFLAGS) -o $@ $< $(DASM)

$(EXE): wang-sim.o $(OBJS) $(XTRA) $(DASM)
	$(CC) $(CFLAGS) -o $@ $< $(OBJS) $(XTRA) $(DASM)

w600_fe.class: w600_fe.java $(COMMON_CLASSES) $(W600_CLASSES)
	javac w600_fe.java

.SUFFIXES: .class .java

.java.class:
	javac $?
	if [[ "$?" == "../common/"* ]]; then \
		mv ../common/$(basename $@)*.class .; \
	fi

clean:
	rm -f *.o

jar: wang600.jar

Manifest.txt:
	echo "Main-Class: w600_fe" >$@

SHIP_DOCS = $(filter-out docs/wang600arch.html,$(wildcard docs/*.html))

wang600.jar: w600_fe.class Manifest.txt
	jar cfm $@ Manifest.txt $(ROM) *.class icons/*.{gif,png} $(SHIP_DOCS) \
		$(SPCL) $(addprefix -C ../common/fonts ,$(FONTS))
