# $Id: Makefile.ship,v 1.1 2012/02/19 23:17:50 drmiller Exp $

COPTS =

VPATH = ../common

CFLAGS += -D__wang600__ -I../common -I.

OBJS = wang_sys.o wang_sim_cmd.o \
	w600_decode.o wang_exec.o wang_gui.o

FONTDIR = $(shell if [[ -d ~/.fonts ]]; then echo ~/.fonts; elif [[ -d ~/Library/Fonts ]]; then echo ~/Library/Fonts; fi)
FONTDEST =
FONTS = $(notdir $(wildcard ../common/fonts/*.ttf))

XTRA = 

DASM = dw600.o loaducode_txt.o

all: w600-sim w600_fe.class

CFLAGS += -g -O3 $(COPTS)

w600-dasm: wang-dasm.o $(DASM)
	$(CC) $(CFLAGS) -o $@ $< $(DASM)

w600-sim: wang-sim.o $(OBJS) $(XTRA) $(DASM)
	$(CC) $(CFLAGS) -o $@ $< $(OBJS) $(XTRA) $(DASM)

w600_fe.class: w600_fe.java
	javac w600_fe.java

clean:
	rm -f *.o

jar: wang600.jar

Manifest.txt:
	echo "Main-Class: w600_fe" >$@

SHIP_DOCS = $(filter-out docs/wang600arch.html,$(wildcard docs/*.html))

wang600.jar: w600_fe.class Manifest.txt
	jar cfm $@ Manifest.txt *.class icons/*.{gif,png} $(SHIP_DOCS) \
		$(addprefix -C ../common/fonts ,$(FONTS))
