#!/bin/sh
# $Id: UNINSTALL,v 1.2 2014/01/16 13:00:08 drmiller Exp $

export INSTALLPATH="${HOME}/wang600apc"

# path might have blanks!!!
cd ${HOME}
echo "Removing ${INSTALLPATH}..."
rm -rf "${INSTALLPATH}"

for app in Wang600.desktop Wang614.desktop; do
	if [[ -d "${HOME}/Desktop/${app}" ]]; then
		echo "Removing GNOME shortcut ${app}..."
		rm -rf "${HOME}/Desktop/${app}"
	fi
done
